name: Build Flatpak bundle
on:
  push:
    branches:
      - org.mozilla.FirefoxESR
  workflow_dispatch:
jobs:
  Build-Flatpak-Bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      # TODO: Specifying runtime version here is prone to future errors.
      - name: Setup dependencies
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y --user org.freedesktop.Sdk/x86_64/22.08
          flatpak install -y --user org.freedesktop.Platform/x86_64/22.08
          flatpak install -y --user org.mozilla.firefox.BaseApp//22.08
      - name: Build flatpak bundle
        run: |
          mkdir out
          flatpak-builder --repo=repo app ./org.mozilla.firefox_esr.json 
          flatpak build-bundle repo out/main.flatpak org.mozilla.firefox_esr
          flatpak build-bundle repo out/locale.flatpak org.mozilla.firefox_esr.Locale --runtime
      - name: Upload bundles
        uses: actions/upload-artifact@v3
        with: 
          name: Bundles
          path: ./out/*.flatpak
          if-no-files-found: error